export const menuItems = [
    {id: 1,
      name: 'Anasayfa',
      link: '/',
      icon: 'AiOutlineHome',
      subMenu: 0,
      categories: [1],
    },
    {
      id: 2,
      name: 'Telegram Grupları',
      link: '/telegram-gruplari',
      icon: 'AiOutlineUnorderedList',
      subMenu: 0,
      categories: [1],
    },
    {
      id: 3,
      name: 'Kaynaklar',
      link: '/kaynaklar',
      icon: 'AiOutlineBook',
      subMenu: 0,
      categories: [1],
    },
    {
      id: 4,
      name: 'İş İlanları',
      link: '/is-ilanlari',
      icon: 'AiOutlineUnorderedList',
      subMenu: 0,
      categories: [1],
    },
    {
      id: 5,
      name: 'Etiketler',
      link: '/etiketler',
      icon: 'AiOutlineTag',
      subMenu: 0,
      categories: [1],
    },
    {
      id: 6,
      name: 'SSS',
      link: '/sss',
      icon: 'AiOutlineQuestionCircle',
      subMenu: 0,
      categories: [1],
    },
    {
      id: 7,
      name: 'Amacimiz',
      link: '/sayfalar/amacimiz',
      icon: 'AiOutlineInfoCircle',
      subMenu: 0,
      categories: [1],
    },
    {
      id: 8,
      name: 'Kurallar',
      link: '/sayfalar/kurallar',
      icon: 'AiOutlineBook',
      subMenu: 0,
      categories: [1]
    },
    {
      id: 9,
      name: 'İletişim',
      link: '/iletisim',
      icon: 'AiOutlinePhone',
      subMenu: 0,
      categories: [1]
    },
  ]
