services:
  frontend:
    container_name: eksicodeFrontend
    build: 
      context: ./frontend
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_STATIC_PAGE_GENERATION_TIMEOUT=180
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - ./frontend:/app/
      - /app/node_modules
      - /app/.next
    restart: on-failure
    networks:
      - eksicode_nw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    container_name: eksicodeBackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - eksicode_nw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  nginx:
    container_name: eksicodeNginx
    image: nginx
    environment:
      - TZ=Europe/Istanbul
      - PROTOCOL=HTTP
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/etc/nginx/logs/
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/cache/:/etc/nginx/cache/
      - ./nginx/eksicode.crt:/etc/nginx/eksicode.crt
      - ./nginx/eksicode.key:/etc/nginx/eksicode.key
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - eksicode_nw
    depends_on:
      backend:
        condition: service_healthy
        restart: true
      frontend:
        condition: service_healthy
        restart: true

volumes:
  backend:
  frontend:
  nginx:

networks:
  eksicode_nw:
