services:

  backend:
    container_name: eksicodeBackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - eksicode_nw
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"]

  frontend:
    container_name: eksicodeFrontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://api-demo.eksicode.org
      - NEXT_STATIC_PAGE_GENERATION_TIMEOUT=180
      - NODE_OPTIONS="--max-old-space-size=4096"
      - NEXT_PUBLIC_API_URL=http://backend:9000
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
    volumes:
      - ./frontend:/app/
      - /app/node_modules
      - /app/.next
    restart: on-failure
    networks:
      - eksicode_nw
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]


  nginx:
    container_name: eksicodeNginx
    image: nginx
    environment:
      - TZ=Europe/Istanbul
      - PROTOCOL=HTTP
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/etc/nginx/logs/
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/cache/:/etc/nginx/cache/
      - ./nginx/eksicode.crt:/etc/nginx/eksicode.crt
      - ./nginx/eksicode.key:/etc/nginx/eksicode.key
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - eksicode_nw
    depends_on:
      backend:
        condition: service_healthy
        restart: true
      frontend:
        condition: service_healthy
        restart: true

volumes:
  backend:
  frontend:
  nginx:

networks:
  eksicode_nw:
